package com.taisf.web.oms.permission.entity;


import com.jk.framework.base.entity.BaseEntity;

import java.util.Date;

/**
 * 
 * <p>后台用户实体类</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author afi
 * @since 1.0
 * @version 1.0
 */
public class CurrentuserEntity extends BaseEntity {
    /**
	 * 序列化id
	 */
	private static final long serialVersionUID = 7527873987270618533L;

	/**
     * 主键id
     * This field corresponds to the database column t_sys_currentuser.id
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private Integer id;

    /**
     * 逻辑id
     * This field corresponds to the database column t_sys_currentuser.fid
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String fid;

    /**
     * 用户名称
     * This field corresponds to the database column t_sys_currentuser.user_account
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String userAccount;

    /**
     * 登录密码
     * This field corresponds to the database column t_sys_currentuser.user_password
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String userPassword;

    /**
     * 关联员工id
     * This field corresponds to the database column t_sys_currentuser.employee_id
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String employeeFid;

    /**
     * 是否管理员 0：否，1：是
     * This field corresponds to the database column t_sys_currentuser.is_admin
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private Integer isAdmin;

    /**
     * 用户状态 0：正常，1：停用
     * This field corresponds to the database column t_sys_currentuser.account_status
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private Integer accountStatus;

    /**
     * 国家标示
     * This field corresponds to the database column t_sys_currentuser.city_code
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String nationCode;
    /**
     * 省标示
     * This field corresponds to the database column t_sys_currentuser.city_code
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String provinceCode;
    /**
     * 城市标示
     * This field corresponds to the database column t_sys_currentuser.city_code
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String cityCode;
	/**
     * 区域标示
     * This field corresponds to the database column t_sys_currentuser.city_code
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String areaCode;

    /**
     * 是否删除 0：否，1：是
     * This field corresponds to the database column t_sys_currentuser.is_del
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private Integer isDel;

    /**
     * 最后更新时间
     * This field corresponds to the database column t_sys_currentuser.last_modify_date
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private Date lastModifyDate;

    /**
     * 添加时间
     * This field corresponds to the database column t_sys_currentuser.create_date
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private Date createDate;

    /**
     * 创建人id
     * This field corresponds to the database column t_sys_currentuser.create_id
     *
     * @mbggenerated Tue Mar 08 15:18:47 CST 2016
     */
    private String createFid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.id
     *
     * @return the value of t_sys_currentuser.id
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.id
     *
     * @param id the value for t_sys_currentuser.id
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.fid
     *
     * @return the value of t_sys_currentuser.fid
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.fid
     *
     * @param fid the value for t_sys_currentuser.fid
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.user_account
     *
     * @return the value of t_sys_currentuser.user_account
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.user_account
     *
     * @param userAccount the value for t_sys_currentuser.user_account
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.user_password
     *
     * @return the value of t_sys_currentuser.user_password
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.user_password
     *
     * @param userPassword the value for t_sys_currentuser.user_password
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.employee_fid
     *
     * @return the value of t_sys_currentuser.employee_fid
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public String getEmployeeFid() {
        return employeeFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.employee_fid
     *
     * @param employeeFid the value for t_sys_currentuser.employee_fid
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setEmployeeFid(String employeeFid) {
        this.employeeFid = employeeFid == null ? null : employeeFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.is_admin
     *
     * @return the value of t_sys_currentuser.is_admin
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public Integer getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.is_admin
     *
     * @param isAdmin the value for t_sys_currentuser.is_admin
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.account_status
     *
     * @return the value of t_sys_currentuser.account_status
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.account_status
     *
     * @param accountStatus the value for t_sys_currentuser.account_status
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.city_code
     *
     * @return the value of t_sys_currentuser.city_code
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.city_code
     *
     * @param cityCode the value for t_sys_currentuser.city_code
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.is_del
     *
     * @return the value of t_sys_currentuser.is_del
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.is_del
     *
     * @param isDel the value for t_sys_currentuser.is_del
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.last_modify_date
     *
     * @return the value of t_sys_currentuser.last_modify_date
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.last_modify_date
     *
     * @param lastModifyDate the value for t_sys_currentuser.last_modify_date
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.create_date
     *
     * @return the value of t_sys_currentuser.create_date
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.create_date
     *
     * @param createDate the value for t_sys_currentuser.create_date
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_currentuser.create_fid
     *
     * @return the value of t_sys_currentuser.create_fid
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public String getCreateFid() {
        return createFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_currentuser.create_fid
     *
     * @param createFid the value for t_sys_currentuser.create_fid
     *
     * @mbggenerated Wed Mar 09 10:41:35 CST 2016
     */
    public void setCreateFid(String createFid) {
        this.createFid = createFid == null ? null : createFid.trim();
    }
    /**
   	 * @return the nationCode
   	 */
   	public String getNationCode() {
   		return nationCode;
   	}

   	/**
   	 * @param nationCode the nationCode to set
   	 */
   	public void setNationCode(String nationCode) {
   		this.nationCode = nationCode;
   	}

   	/**
   	 * @return the provinceCode
   	 */
   	public String getProvinceCode() {
   		return provinceCode;
   	}

   	/**
   	 * @param provinceCode the provinceCode to set
   	 */
   	public void setProvinceCode(String provinceCode) {
   		this.provinceCode = provinceCode;
   	}

   	/**
   	 * @return the areaCode
   	 */
   	public String getAreaCode() {
   		return areaCode;
   	}

   	/**
   	 * @param areaCode the areaCode to set
   	 */
   	public void setAreaCode(String areaCode) {
   		this.areaCode = areaCode;
   	}
}