package com.taisf.services.ups.entity;


import com.jk.framework.base.entity.BaseEntity;

/**
 * 
 * <p>角色资源实体</p>
 * 
 * <PRE>
 * <BR>	修改记录
 * <BR>-----------------------------------------------
 * <BR>	修改日期			修改人			修改内容
 * </PRE>
 * 
 * @author liujun
 * @since 1.0
 * @version 1.0
 */
public class RoleResourceEntity extends BaseEntity {
    /**
	 *序列化实体 
	 */
	private static final long serialVersionUID = -1071530545997814031L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_resource.id
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_resource.role_fid
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    private String roleFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_resource.resource_fid
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    private String resourceFid;

    /**
     * 
     * This method returns the value of the database column t_sys_role_resource.id
     *
     * @return the value of t_sys_role_resource.id
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * 
     * This method sets the value of the database column t_sys_role_resource.id
     *
     * @param id the value for t_sys_role_resource.id
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 
     * This method returns the value of the database column t_sys_role_resource.role_fid
     *
     * @return the value of t_sys_role_resource.role_fid
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    public String getRoleFid() {
        return roleFid;
    }

    /**
     * 
     * This method sets the value of the database column t_sys_role_resource.role_fid
     *
     * @param roleFid the value for t_sys_role_resource.role_fid
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    public void setRoleFid(String roleFid) {
        this.roleFid = roleFid == null ? null : roleFid.trim();
    }

    /**
     * 
     * This method returns the value of the database column t_sys_role_resource.resource_fid
     *
     * @return the value of t_sys_role_resource.resource_fid
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    public String getResourceFid() {
        return resourceFid;
    }

    /**
     * 
     * This method sets the value of the database column t_sys_role_resource.resource_fid
     *
     * @param resourceFid the value for t_sys_role_resource.resource_fid
     *
     * @mbggenerated Fri Mar 11 20:50:35 CST 2016
     */
    public void setResourceFid(String resourceFid) {
        this.resourceFid = resourceFid == null ? null : resourceFid.trim();
    }
}